# Generated by Django 5.0.6 on 2024-10-24 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('publication_type', models.CharField(choices=[('article', 'Article'), ('review', 'Review'), ('caseReport', 'Case Report')], max_length=100)),
                ('article_type', models.CharField(choices=[('originalResearch', 'Original Research'), ('clinicalTrial', 'Clinical Trial'), ('metaAnalysis', 'Meta Analysis')], max_length=100)),
                ('date_of_publication', models.DateField()),
                ('abstract', models.TextField()),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('pubmed_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scopus_link', models.URLField(blank=True, null=True)),
                ('uploaded_files', models.FileField(blank=True, null=True, upload_to='journal_files/')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('repost', 'Repost'), ('journal', 'Journal')], default='post', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='socialmedia.journal'),
        ),
    ]
