# Generated by Django 5.0.6 on 2024-12-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0009_user_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility_type',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('private', 'Private'), ('public', 'Public')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='email_vis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_vis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='website_vis',
            field=models.BooleanField(default=False),
        ),
    ]
