# Generated by Django 5.0.6 on 2024-12-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0010_post_visibility_type_user_email_vis_user_phone_vis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
