# Generated by Django 5.0.6 on 2024-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0011_alter_user_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('self_employed', 'Self-employed'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('seasonal', 'Seasonal')], default='full_time', max_length=20),
        ),
    ]
