# Generated by Django 5.0.6 on 2024-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0012_jobexperience_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='job_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='on_site', max_length=20),
        ),
    ]
