# Generated by Django 5.0.6 on 2024-12-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0013_jobexperience_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexperience',
            name='department',
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='end_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='start_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10, null=True),
        ),
    ]
